# Generated by Django 3.2.2 on 2021-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=250)),
                ('dosage', models.CharField(max_length=250)),
            ],
        ),
    ]
