# Generated by Django 3.2.2 on 2021-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ingredient',
            field=models.CharField(max_length=300),
        ),
    ]
