# Generated by Django 3.2.2 on 2021-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_medicine_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETC_Info',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('caution', models.TextField(null=True)),
                ('nation', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OTC_Info',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=255)),
                ('effect', models.TextField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('caution', models.TextField(null=True)),
                ('nation', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OTC_Shape',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('frontmark', models.CharField(max_length=30, null=True)),
                ('backmark', models.CharField(max_length=30, null=True)),
                ('shape', models.CharField(max_length=5, null=True)),
                ('frontcolor', models.CharField(max_length=10, null=True)),
                ('backcolor', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
