# Generated by Django 3.2.2 on 2021-05-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_etc_info_otc_info_otc_shape'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETC_Info',
            new_name='ETCInfo',
        ),
        migrations.RenameModel(
            old_name='OTC_Info',
            new_name='OTCInfo',
        ),
        migrations.RenameModel(
            old_name='OTC_Shape',
            new_name='OTCShape',
        ),
    ]
