# Generated by Django 3.2.2 on 2021-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210524_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etcinfo',
            name='dosage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otcinfo',
            name='dosage',
            field=models.CharField(max_length=255),
        ),
    ]
