# Generated by Django 3.2.2 on 2021-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210525_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTCShape',
        ),
        migrations.AlterField(
            model_name='etcinfo',
            name='dosage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='etcinfo',
            name='effect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='otcinfo',
            name='dosage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='otcinfo',
            name='effect',
            field=models.TextField(),
        ),
    ]
