# Generated by Django 3.2.2 on 2021-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210528_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='bcolor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='bmark',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
