# Generated by Django 3.2.2 on 2021-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210528_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
        migrations.AlterField(
            model_name='pill',
            name='fmark',
            field=models.CharField(max_length=20),
        ),
    ]
