# Generated by Django 3.2.2 on 2021-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210528_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='bcolor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pill',
            name='bmark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='fmark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
