# Generated by Django 3.2.2 on 2021-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210530_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='bmark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
